name: BlockDefense
version: '1.0'
main: org.blockDefense.BlockDefense
api-version: '1.20'
authors: [ AluminumNitrate, Jason31416 ]
description: A Tower Battle in Minecraft

commands:
  blockdefense:
    description: Main command of the BlockDefense plugin.
    aliases: [bd]
    usage: /blockdefense <subCommand>